In [20]:
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/tigarto/repaso_python/blob/master/funciones.ipynb)

SyntaxError: invalid syntax (<ipython-input-20-94960b4e0344>, line 1)

In [3]:
import numpy as np

### Ejemplos

#### **Problema 1**

Teniendo en cuenta las siguientes formulas:

$mean = \frac{\sum_{i=1}^{n}x_i}{n} = \frac{x_1 + x_2 + ... + x_n}{n}$

$desviation = \sqrt{\frac{\sum_{i=1}^{n}(x^i - mean)^2}{n-1}} $

El programa deberá contener las siguientes funciones:

```python
# Calcula la desviacion estandar de una lista de valores
def deviation(x):
  # Codigo solucion...

# Calcule la media de una lista de valores
def mean(x):
  # Codigo solucion...
```
Escriba un programa de test que solicite al usuario una lista de numeros y despliegue la media y la desviación estandar, como en el siguiente programa:

```
Digite los numeros: 1.9 2.5 3.7 2 1 6 3 4 5 2
La media es 3.11
La desviacion estandar es 1.55738
```


* **Solución a punta de listas**:

In [4]:
import math

# Funcion que calcula la desviacion estandar de una lista de valores
def deviation(x: list) -> float:
    media = mean(x)
    suma = 0
    tam = len(x)
    for x_i in x:
        suma += (x_i - media)**2
    prom = suma/(tam - 1)
    return math.sqrt(prom)
     
# Funcion que calcula la media de una lista de valores    
def mean(x: list) -> float:
    suma = sum(x)
    tam = len(x)
    media = suma/tam
    return media

""" Programa de test """
arreglo = input("Digite los numeros: ")
arreglo = arreglo.split()
arreglo_float = []
# Convirtiendo cada elemento string en float
for e in arreglo:
    arreglo_float += [float(e)]

media = mean(arreglo_float)
desv = deviation(arreglo_float)
print("La media es: " + str(media))
print("La desviacion estandar es: " + str(desv))
    

Digite los numeros: 1.9 2.5 3.7 2 1 6 3 4 5 2
La media es: 3.1100000000000003
La desviacion estandar es: 1.5573838462127583


* **Solución empleando numpy**:

In [6]:
""" Programa de test """
arreglo = input("Digite los numeros: ")
arreglo = arreglo.split()
arreglo_float = []
# Convirtiendo cada elemento string en float
for e in arreglo:
    arreglo_float += [float(e)]

media = np.mean(np.array(arreglo_float))   
desv = np.std(np.array(arreglo_float),ddof = 1)
print("La media es: " + str(media))
print("La desviacion estandar es: " + str(desv))

Digite los numeros: 1.9 2.5 3.7 2 1 6 3 4 5 2
La media es: 3.1100000000000003
La desviacion estandar es: 1.5573838462127583


#### **Problema 2**
Realizar 2 funciones que hagan lo siguiente:
1. **inicializarMatrixConstante**: Inicializar una matrix de dos dimensiones con un valor constante dado K.
2. **imprimirMatrix**: Funcion que imprime una matrix dada

* **Solución a punta de listas**:

In [9]:
def inicializarMatrixConstante(fil, col, K = 0):
    matrix = []
    for i in range(fil):
        fila = []
        for j in range(col):
            fila.append(K)    # fila += [K]
        matrix.append(fila)   # matrix += [fila] 
    return matrix

def imprimirMatrix(M):
    FILAS = len(M)
    COLUMNAS = len(M[0])
    for i in range(FILAS):
        print("[ ", end = "")
        for j in range(COLUMNAS):
            print(str(M[i][j]) + " ", end = "")
        print("]")
    
    
""" Testeando el correcto funcionamiendo de las funciones """    
# Testing de la funcion inicializarMatrixConstante
M1 = inicializarMatrixConstante(4,3)
M2 = inicializarMatrixConstante(3,6, -1.2)

# # Testing de la funcion imprimirMatrix
print("M1 = ")
imprimirMatrix(M1)
print()
print("M2 = ")
imprimirMatrix(M2)

M1 = 
[ 0 0 0 ]
[ 0 0 0 ]
[ 0 0 0 ]
[ 0 0 0 ]

M2 = 
[ -1.2 -1.2 -1.2 -1.2 -1.2 -1.2 ]
[ -1.2 -1.2 -1.2 -1.2 -1.2 -1.2 ]
[ -1.2 -1.2 -1.2 -1.2 -1.2 -1.2 ]


* **Solución empleando numpy**:

In [10]:
M1 = np.full([4,3], 0)
print("M1 = ")
print(M1)
print()
M2 = np.full([3,6], -1.2)
print("M2 = ")
print(M2)

M1 = 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

M2 = 
[[-1.2 -1.2 -1.2 -1.2 -1.2 -1.2]
 [-1.2 -1.2 -1.2 -1.2 -1.2 -1.2]
 [-1.2 -1.2 -1.2 -1.2 -1.2 -1.2]]


#### **Problema 3**

Realizar una funcion es lea una matriz de dos dimensiones y calcular la suma de cada una de sus filas y columnas, dejando dichos resultados en dos vectores, uno de la suma de las filas y otro de las columnas.

* **Solución a punta de listas**:

In [ ]:
def imprimirMatrix(M):
    FILAS = len(M)
    for i in range(FILAS):
        print(M[i])
        
def obtenerSumaColumnas(M):
    FILAS = len(M)
    COLUMNAS = len(M[0])
    sumCols = []
    for i in range(COLUMNAS):
        sumCol = 0
        for j in range(FILAS):
            sumCol += M[j][i] 
        sumCols.append(sumCol)
        sumCol = 0
    return sumCols
            
def obtenerSumaFilas(M):
    FILAS = len(M)
    COLUMNAS = len(M[0])
    sumFilas = []
    for i in range(FILAS):
        sumFila = 0
        for j in range(COLUMNAS):
            sumFila += M[i][j] 
        sumFilas.append(sumFila)
    return sumFilas

def sumDimMatrix(M):
    sumC = obtenerSumaColumnas(M)
    sumF = obtenerSumaFilas(M)
    return [sumF, sumC]


matrixTest = [[2, 3, -10],[8, 0, 5]]
imprimirMatrix(matrixTest)
sumaFilas = obtenerSumaFilas(matrixTest)
sumaColumnas = obtenerSumaColumnas(matrixTest)
sumaDimensiones = sumDimMatrix(matrixTest)
print()
print("Suma filas:", sumaFilas)
print("Suma columnas:", sumaColumnas)
print("Suma dimensiones:", sumaDimensiones)

* **Solución empleando numpy**:

In [11]:
matrixTest = [[2, 3, -10],[8, 0, 5]]
sumaFilas = np.sum(matrixTest, axis=0)
sumaColumnas = np.sum(matrixTest, axis=1)
print()
print("Suma filas:", sumaFilas)
print("Suma columnas:", sumaColumnas)



Suma filas: [10  3 -5]
Suma columnas: [-5 13]


#### **Problema 4**
* Realizar una función que pida dos matrices y retorne una tercera con el resultado de la suma.
* Realizar una funcion que imprima una matriz
* Realizar una funcion que retorne el valor de la suma de los elementos de una matriz


* **Solución a punta de listas**:

* **Solución empleando numpy**:

In [13]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[4, 2, 8],[-10, 9, 7]])
C = A + B
print(A)
print(B)
print(20*"-")
print(C)

[[1 2 3]
 [4 5 6]]
[[  4   2   8]
 [-10   9   7]]
--------------------
[[ 5  4 11]
 [-6 14 13]]


#### **Problema 5**
Se dispone de N temperaturas almacenadas en un array. Se desea calcular su media y obtener el número de temperaturas mayores o iguales que la media.

* **Solución a punta de listas**:

* **Solución empleando numpy**:

In [19]:
np.random.seed(0)

Temp = np.random.rand(4,6)*10
print(Temp)
maxTemp = np.amax(Temp)
minTemp = np.amin(Temp)
media = np.mean(Temp)
print()
print("media =",media)
Temp_meq_media = len(np.where(Temp >= media)[0])
print()
print(Temp_meq_media)

[[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761 3.83441519 7.91725038 5.2889492 ]
 [5.68044561 9.25596638 0.71036058 0.871293   0.20218397 8.32619846]
 [7.78156751 8.70012148 9.78618342 7.99158564 4.61479362 7.80529176]]

media = 6.104534139767009

12


#### **Problema 6**

La matriz T representa una tabla de anotaciones de saltos de altura (primer salto), donde las filas representan el nombre del atleta y las columnas las diferentes alturas saltadas por el atleta. Los símbolos almacenados en la tabla son: 
* **x**: Salto válido
* **o**: salto nulo o no intentado.

![saltos](saltos.jpg)

Se pide:
1. Hacer la representación matricial de la tabla.
2. Hacer una función que imprima la tabla.

**Nota**: Consulte los métodos de la clase string en: [https://www.w3schools.com/python/python_ref_string.asp](https://www.w3schools.com/python/python_ref_string.asp)

In [ ]:
saltos = [
           ['x', 'o', 'x', 'x', 'x', 'o'], 
           ['o', 'x', 'x', 'o', 'x', 'o'],
           ['o', 'o', 'o', 'o', 'o', 'o'],
           ['o', 'o', 'o', 'x', 'x', 'x']
         ]

nombres = ['Garcia', 'Perez', 'Gil', 'Mortimer']
alturas = ['2.00', '2.10', '2.20', '2.30', '2.35', '2.40']

def imprimirTabla():
    global saltos; nombres; alturas
    tabla = [alturas] + saltos
    # print(tabla)
    for i in range(1,len(tabla)):
        tabla[i] = [nombres[i - 1]] + tabla[i]
    # print(tabla)
    """ Imprimiendo la primera fila de la tabla """
    print(''.ljust(10,' '), end = '')
    for i in range(0, len(tabla[0])):
        print(tabla[0][i].ljust(10,' '), end = '')
    print()
    print(70*"-")
    """ Imprimiendo las filas asociadas a cada nadador """
    for i in range(1, len(tabla)):
        for j in range(len(tabla[i])):
            print(tabla[i][j].ljust(10,' '), end = '')
        print()
    
    
    
imprimirTabla()