[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/tigarto/python_mision_codes/blob/main/semana4/clases_python_6.ipynb)

In [8]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# **Numpy**


## **Características generales**

* **Numpy (Numeric Python)** ([https://numpy.org/](https://numpy.org/)) es una librería open source para Python que proporciona
rápidas funciones pre compiladas para rutinas matemáticas y numéricas.
* Facilita mediante poderosas estructuras de datos y funciones el procesamiento datos con arreglos de múltiples dimensiones y matrices.

### **Usando Numpy**

Antes de usar numpy esta debe ser importada. Esto puede ser hecho de dos formas:

**Forma 1**: Simplemente importando la libreria **numpy**.

```python
import numpy
```

**Forma 2**: Importanto la libreria **numpy** y renombrandola como **np**. (Forma recomenda)

```python
import numpy as np
```

In [1]:
import numpy as np

## **Array**

Un Array es un tipo de dato compuesto a partir de tipos de datos sencillos. Como un Array es un objeto tiene propiedades y métodos los cuales se pueden consultar accediendo a la documentación online ([https://numpy.org/doc/stable/](https://numpy.org/doc/stable/)) o mediante la función **help** en el interprete:

```python
help(np.array)
```

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

### **Propiedades de los Arrays (np.array)**

|Propiedad |Descripción|
|:---|:---|
|```shape```|Tupla con las dimensiones.|
|```ndim```|Numero de dimensiones.|
|```size```|Numero de elementos.|
|```itemsize```|Tamaño de uno de los elementos en bytes.|
|```nbytes```|Tamaño total ocupado por los elementos.|
|```dtype```|Tipo de dato de los elementos.|
|```real```|Parte real.|
|```imag```|Parte imaginaria.|

In [6]:
# Funciones de utilidad
A = np.array([[1 , 2, 3],[4, 5, 6]])
print(A)        # Imprimiendo el vector
print(A.shape)  # Numero de filas y columnas
filas = A.shape[0]
columnas = A.shape[1]
print("Filas:", filas)
print("Columnas:", columnas)

[[1 2 3]
 [4 5 6]]
(2, 3)
Filas: 2
Columnas: 3


#### **Comparando listas con np.array**

Supongase que se desea convertir las siguientes temperaturas en grados centigrados: 25.3, 24.8, 26.9, 23.9 a grados Fahrenheit. Recuerde que la formula de conversión es:

$F = \frac{9}{5}C + 32$

In [11]:
# Usando arrays normales
cvalues = [25.3, 24.8, 26.9, 23.9]

# fvalues = [ x*9/5 + 32 for x in cvalues]
fvalues = []
for i in range(len(cvalues)):
    f_valor = cvalues[i]*9/5 + 32
    fvalues.append(f_valor)
print(cvalues)
print(fvalues)

[25.3, 24.8, 26.9, 23.9]
[77.54, 76.64, 80.42, 75.02]


In [8]:
# Usando np.array
c = np.array([25.3, 24.8, 26.9, 23.9])
f = c*9/5 + 32
print(c)
print(f)

[25.3 24.8 26.9 23.9]
[77.54 76.64 80.42 75.02]


### **Creación de Arrays usando numpy**

Hay varias formas, a continuación se muestran las principales formas de :
1. A partir de secuencias (listas o tuplas) de Python.
2. Haciendo uso de funciones propias de Numpy.
3. Copiando otro array.
4. Lectura de datos desde Fichero.

#### **1. A partir de secuencias (listas o tuplas) de Python**

```python
np.array(secuencia)
```

In [21]:
tupla = (3, 5, 7.7)
A1 = np.array(tupla)
lista = [1, 2, 3, 8]
A2 = np.array(lista)
print(A1)
print(A2)

[3.  5.  7.7]
[1 2 3 8]


#### **2. Haciendo uso de funciones propias de Numpy**

a. **Usando la función numpy.arange**

```python
numpy.arange([start], stop[, step], dtype=None)
```

Aspectos claves:
* Equivalente a la función range(start, stop, step) de Python.
* A diferencia de la función range el step puede ser decimal.
* El extremo final del intervalo (stop) no se incluye.

Para mas información puede consultar en el siguiente [link](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange)



In [22]:
R1 = np.arange(5,6,0.1)
R2 = np.arange(3)
R3 = np.arange(3,0.5)
print(R1)
print(R2)
print(R3)

[5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
[0 1 2]
[]


b. **Usando la función numpy.linspace**

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False)
```

Devuelve un array en el que se ha dividido el intervalo **[start, stop]** (endpoint=True, por defecto) en **num** fragmentos.

Para mas información puede consultar en el siguiente [link](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace)



In [23]:
A = np.linspace(5, 6, 5)
print(A)
B = np.linspace(5, 6, 5, False, True)
print(B)

[5.   5.25 5.5  5.75 6.  ]
(array([5. , 5.2, 5.4, 5.6, 5.8]), 0.2)


c. **Función numpy.ones**

Esta función genera un array de 1's.

```python
numpy.ones(shape, dtype=None)
```

* **shape**: Forma del array de salida (entero o lista/tupla). Si se pasa una lista o tupla, se crea un array n-dimensional con la forma (shape) dada por la lista/tupla.
* **dtype**: cualquiera de los tipos de datos de numpy (para mas información sobre numpy.dtype puede consultar el siguiente [link](https://numpy.org/doc/stable/reference/generated/numpy.dtype.html#numpy.dtype)).

In [32]:
A = np.ones(4, dtype = np.dtype(float))
print("A: ")
print(A)

B = np.ones([2,3])
print("B: ")
print(B)

C = np.ones((3,2), dtype = np.dtype(int))
print("C: ")
print(C)

A: 
[1. 1. 1. 1.]
B: 
[[1. 1. 1.]
 [1. 1. 1.]]
C: 
[[1 1]
 [1 1]
 [1 1]]


d. **Función numpy.zeros**

Funcion que genera un array de 0's.

```python
numpy.zeros(shape, dtype=float)
```

Sigue el mismo comportamiento de la función **numpy.ones**. ([link](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)).

In [35]:
M1 = np.zeros(4, dtype = np.dtype(int))
print("M1: ")
print(M1)

M2 = np.zeros([3,5])
print("M2: ")
print(M2)

M1: 
[0 0 0 0]
M2: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


e. **Función numpy.eye**

Funcion que crea la matriz identidad.

```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>)
```

Para mas información puede consultar el siguiente [link](https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye).

In [38]:
I1 = np.eye(3, dtype = np.dtype(int))
print("I1: ")
print(I1)

I2 = np.eye(3, 4)
print("I2: ")
print(I2)

I3 = np.eye(4, k = 1,dtype = np.dtype(int))
print("I3: ")
print(I3)

I1: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
I2: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
I3: 
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


f. **Función numpy.diag**

Extrae una diagonal o construye un array diagonal

```python
numpy.diag(v, k=0)
```

Para mas información puede consultar el siguiente [link](https://numpy.org/doc/stable/reference/generated/numpy.diag.html?highlight=diag#numpy.diag).

In [40]:
M1 = np.diag([1,2,3])
print("M1: ")
print(M1)

M2 = np.diag([1,2,3,4],2)
print("M2: ")
print(M2)

A = np.array([[1, 2, 3],[4, 5,6],[7, 8, 9]])
print("A: ")
print(A)

M3 = np.diag(A)
print("M3: ")
print(M3)

M1: 
[[1 0 0]
 [0 2 0]
 [0 0 3]]
M2: 
[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
M3: 
[1 5 9]


#### **3. Mediante copia de otro array**

Existen dos formas:
1. Copia por referencia
2. Copia por valor

a. **Copia por referencia**

* Se emplea el operador de asignación (=).
* Cuando se hace esto tanto el array original como la copia comparten memoria (aliasing)

In [42]:
a = np.arange(3)
b = a
print(a)
b[0] = -3
print()
print(b)
print(a)

[0 1 2]

[-3  1  2]
[-3  1  2]


b. **Copia por valor**

* El propósito es que original y copia sean objetos diferentes. Esto se puede hacer:
  * Mediante una operación aritmética
  * Mediante la function copy de numpy.

In [43]:
# Mediante operacion aritmetica
a = np.arange(3)
print(a)
b = a + 0
b[0] = -3
print()
print(b)
print(a)

[0 1 2]

[-3  1  2]
[0 1 2]


In [44]:
# Mediante operacion aritmetica
a = np.arange(3)
print(a)
b = a.copy()
b[0] = -3
print()
print(b)
print(a)

[0 1 2]

[-3  1  2]
[0 1 2]


### **Indexación**
* Cuando se habla de indexación nos referimos a la selección de elementos concretos del array.
* **A tener en cuenta**: Se accede a un elemento del array dando su posición en el array, mediante un índice entero entre corchetes ('[]')

```python
nombre_array[posicion]
```
* El primer índice es el 0 (Como en C/C++ o Java), aunque también se soporta indexación negativa.
* Si el índice es mayor que el numero de elementos de array, lanzara una excepción (IndexError).

In [46]:
A = np.arange(1,9,2)
print(A)
print(A[0])
print(A[-1])
print(A[3])
print(A[4]) # ERROR

[1 3 5 7]
1
7
7


IndexError: index 4 is out of bounds for axis 0 with size 4

#### **Formas de indexación**


|Tipo de selección|Sintaxis|
|:---|:---|
|Un solo elemento | ```array[posicion]```|
|Varios elementos consecutivos | ```array[inicio:fin]```|
|Elementos en un orden cualquiera (Novedad respecto al core de Python)|```array[[p1, p2, ..., pn]]``` <br><br> Donde ```[p1, p2, …, pn]``` es una lista o array |

In [4]:
# Ejemplos
a = np.arange(10)
print("a =",a)
print()
print("a[1] = " + str(a[1]))
print("a[-1] = " + str(a[-1]))
print("a[3:-4] =",a[3:-4])
print("a[3:6] =",a[3:6])
print("a[0:9:2] =",a[0:9:2])
print("a[:4] =",a[:4])
print("a[[1, 5, 2]] =",a[[1, 5, 2]])


a = [0 1 2 3 4 5 6 7 8 9]

a[1] = 1
a[-1] = 9
a[3:-4] = [3 4 5]
a[3:6] = [3 4 5]
a[0:9:2] = [0 2 4 6 8]
a[:4] = [0 1 2 3]
a[[1, 5, 2]] = [1 5 2]


In [2]:
# Ejemplos
# M = np.arange(7).reshape(3,3) ERROR
M = np.arange(9).reshape(3,3)
print("M: ")
print(M)
M[1,2] = -M[2,0]
print(M)
print()
print("M[1][1] = " + str(M[1][1]))
print("M[(2,2)] =", M[(2,2)]) 

M: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4 -6]
 [ 6  7  8]]

M[1][1] = 4
M[(2,2)] = 8


### **Arrays de N-dimensiones**
Se puede modificar un array existente:
1. Haciendo usao de la propiedad **shape**:

In [8]:
a = np.ones(10,dtype = int)
print(a.shape)
print("a = "+ str(a))
a.shape = [2, 5]
print()
print("a: \n"+ str(a))

(10,)
a = [1 1 1 1 1 1 1 1 1 1]

a: 
[[1 1 1 1 1]
 [1 1 1 1 1]]


2. Haciendo uso del método **reshape**:

In [10]:
a = np.ones(10,dtype = int)
print(a.shape)
b = a.reshape((2, 5)) # lista o tupla
print("a: \n"+ str(a))
print()
print("b: \n"+ str(b))


(10,)
a: 
[1 1 1 1 1 1 1 1 1 1]

b: 
[[1 1 1 1 1]
 [1 1 1 1 1]]


#### **Indexado de Arrays de N-dimensiones**

Por medio del indexado se puede acceder a uno o varios elementos del array N-dimensional. La siguiente tabla muestra las diferentes formas de indexar:

|Forma|Sintaxis|
|:---|:---|
|Separandando los índices por comas | ```nombreArray[indexDim1, indexDim2, ..., indexDimN]```|
|Como las listas|```nombreArray[indexDim1][ indexDim2]...[indexDimN]```|
|Usando tuplas| ```nombreArray[(indexDim1, indexDim2, ..., indexDimN)]```|

**Se puede usar el operador []**: para acceder a rangos de elementos tal como para el caso de los arrays de una dimensión.

In [11]:
# M = np.arange(7).reshape(3,3) ERROR
M = np.arange(9).reshape(3,3)
print("M = ")
print(M)
M[1,2] = -M[2,0]
print()
print("M = ")
print(M)
print()
print("M[1][1] = " + str(M[1][1]))
print("M[(2,2)] = " + str(M[(2,2)]))

M = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

M = 
[[ 0  1  2]
 [ 3  4 -6]
 [ 6  7  8]]

M[1][1] = 4
M[(2,2)] = 8


In [21]:
a = np.linspace(0, 1, 5)
print("a =",a)
print("a[:] =",a[:])
print("a[:3] =",a[:3])
print()
b = np.arange(1,10).reshape((3, 3))
print("b:")
print(b)
print()
print("b[-1][-1] =",b[-1][-1])
print()
print("b[-1][:] =",b[-1][:])
print()
print("b[: ,1] =",b[:,1])
print()
print("b[:,:] =\n",b[:,:])
print()
print("b[:] =\n",b[:])

a = [0.   0.25 0.5  0.75 1.  ]
a[:] = [0.   0.25 0.5  0.75 1.  ]
a[:3] = [0.   0.25 0.5 ]

b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

b[-1][-1] = 9

b[-1][:] = [7 8 9]

b[: ,1] = [2 5 8]

b[:,:] =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[:] =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## **Referencias**

* https://www.python-course.eu/numpy.php
* https://numpy.org/learn/ 
* http://facundoq.github.io/courses/images/res/03_numpy.html
* https://github.com/hmedrano/curso-python-cientifico/blob/master/README.md
* http://www.denebola.org/japp/CC/numpy.html
* https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md
* https://numpy.org/doc/stable/user/tutorials_index.html
* https://notebook.community/
* https://notebook.community/jorgemauricio/INIFAP_Course/ejercicios/Numpy/5_Ejercicios%20Numpy-Solucion
